[package]
name = "jet-proto"
version = "0.0.0"
edition = "2021"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
publish = false

[dependencies]
log = "0.4.19"
byteorder = "1.4.3"
uuid = { version = "1.3.3", features = ["v4"] }
httparse = "1.8.0"
http = "0.2.9"

[dev-dependencies]
lazy_static = "1.4.0"
bytes = "1.4.0"
sspi = "0.8.1"
ureq = { version = "2.6.2", features = ["json"] }
url = "2.4.0"
x509-parser = "0.15.0"
exitcode = "1.1.2"
tempfile = "3.6.0"
hex-literal = "0.4.1"
tokio-rustls = { version = "0.24", features = ["dangerous_configuration", "tls12"] }
serde = "1.0.163"
serde_derive = "1.0.162"
serde_json = "1.0.97"
