[package]
name = "benchmark"
version = "0.1.0"
authors = ["Vlad Alex <vlad.al.dp@gmail.com>",
            "Vladyslav Hordiienko <hord.vlad@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
uuid = "0.8"
http = "0.1"
jet-proto = { path = "../jet-proto" }
