version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "CBenoit"
    open-pull-requests-limit: 3
    groups:
      ironrdp:
        patterns:
          - "ironrdp*"
      ironvnc:
        patterns:
          - "ironvnc*"
      serde:
        patterns:
          - "serde*"
      tokio:
        patterns:
          - "tokio*"
      tracing:
        patterns:
          - "tracing*"
      http:
        patterns:
          - "*hyper*"
          - "*axum*"
          - "*tower*"
          - "*openssl*"
          - "*rustls*"
          - "*schannel*"
          - "base64"
          - "tokio-tungstenite"
          - "reqwest"
      crypto:
        patterns:
          - "picky*"
          - "sspi*"
          - "md-5"
          - "md5"
          - "sha1"
          - "pkcs1"
          - "x509-cert"
          - "der"
          - "*rand*"
          - "argon2"
          - "zeroize"
      patch:
        dependency-type: "production"
        update-types:
          - "patch"
      dev:
        dependency-type: "development"
