[package]
name = "subscriber-dummy"
version = "0.1.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = ["."]

[dependencies]
axum = "0.5"
hyper = "0.14"
tokio = { version = "1.20", features = ["full"] }
