[package]
name = "jmux-proto"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
bytes = "1.11"
smol_str = "0.3"

[dev-dependencies]
proptest = "1.7"
jmux-generators = { path = "../jmux-generators" }
