[package]
name = "test-utils"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
transport = { path = "../transport" }
tokio = { version = "1.39", features = ["io-util"] }
tokio-tungstenite = "0.23"
futures-util = "0.3"
proptest = "1.5"
anyhow = "1.0"
portpicker = "0.1"
