[package]
name = "jetsocat-proxy"
version = "0.1.0"
authors = ["Devolutions Inc."]
edition = "2021"
description = "HTTP(S)/SOCKS proxy clients and acceptors implementations for jetsocat"

[[bin]]
name = "socks5_server"
required-features = ["tokio/rt", "tokio/net", "tokio/rt-multi-thread", "tokio/macros", "tokio/io-util"]

[[bin]]
name = "tester"
required-features = ["tokio/rt", "tokio/net"]

[dependencies]
tokio = { version = "1.13.0", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.13.0", features = ["io-util", "rt", "macros", "net"] }

