[package]
name = "proxy-tester"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.20.1", features = ["rt", "net"] }
proxy-http = { path = "../proxy-http" }
proxy-socks = { path = "../proxy-socks" }
