[package]
name = "proxy-socks"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
description = "SOCKS proxy clients and acceptors"
publish = false

[lints]
workspace = true

[dependencies]
proxy-types = { path = "../proxy-types" }
tokio = { version = "1.42", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.42", features = ["rt", "macros"] }
tokio-test = "0.4"
proptest = "1.5"
proxy-generators = { path = "../proxy-generators" }
