[package]
name = "traffic-audit-libsql"
version = "0.0.0"
edition = "2024"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
async-trait = "0.1"
libsql = { version = "0.9", default-features = false, features = ["core", "serde"] }
tracing = "0.1"
traffic-audit.path = "../traffic-audit"
ulid = "1"
uuid = "1.17"

[dev-dependencies]
tempfile = "3.24"
tokio = { version = "1", features = ["time", "macros", "rt", "rt-multi-thread"] }
