[package]
name = "network-scanner-proto"
version = "0.0.0"
authors = [
    "Devolutions Inc. <infos@devolutions.net>",
    "Jeremy Wall <jeremy@marzhillstudios.com>",
    "Jon Grimes <jonkgrimes@gmail.com>"
]
edition = "2021"
publish = false
license = "MIT, Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
byteorder = "1.5.0"
