[package]
name = "job-queue-libsql"
version = "0.0.0"
edition = "2021"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
async-trait = "0.1"
job-queue = { path = "../job-queue" }
libsql = "0.6"
serde = "1"
time = { version = "0.3", default-features = false, features = ["std"] }
tracing = "0.1"
typed-builder = "0.19"
ulid = { version = "1.1", features = ["uuid"] }
uuid = "1.11"
