[package]
name = "win-api-wrappers"
version = "0.0.0"
edition = "2021"
license = "MIT/Apache-2.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
description = "Idiomatic and safe wrappers around the Windows API"
publish = false

[dependencies]
base16ct = { version = "0.2", features = ["alloc"] }
anyhow = "1"
thiserror = "2"
tracing = "0.1"
uuid = { version = "1.17", features = ["v4"] }
widestring = "1.2.0"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_NetManagement",
    "Win32_Security_Authentication_Identity",
    "Win32_Security_Authorization",
    "Win32_Security_Cryptography_Catalog",
    "Win32_Security_Cryptography_Sip",
    "Win32_Security_Cryptography",
    "Win32_Security_WinTrust",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Environment",
    "Win32_System_GroupPolicy",
    "Win32_System_IO",
    "Win32_System_SystemInformation",
    "Win32_System_Kernel",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_Pipes",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_RemoteDesktop",
    "Win32_System_Rpc",
    "Win32_System_StationsAndDesktops",
    "Win32_System_SystemServices",
    "Win32_System_Services",
    "Win32_System_Threading",
    "Win32_System_WinRT",
    "Win32_UI_Controls",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "implement",
]

[dev-dependencies]
rstest = "0.24"

[lints]
workspace = true
