[package]
name = "generate-openapi"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2024"
publish = false

[dependencies]
devolutions-gateway = { path = "../../devolutions-gateway", features = ["openapi"] }
devolutions-pedm = { path = "../../crates/devolutions-pedm" }
serde_yaml = "0.9"
utoipa = { version = "4.2", default-features = false, features = ["uuid", "chrono", "yaml", "time"] }
