name: Create Comment

on:
  pull_request:
    branches: [ master ]
    types: [ opened, labeled ]

jobs:
  create-comment:
    name: Create Comment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/create-comment
        if: ${{ github.event.action == 'opened'}}
        template: ${{ github.workspace }}/.github/comments/pr_greetings.md

      - uses: ./.github/actions/create-comment
        if: ${{ github.event.pull_request.user.login != 'CBenoit' }}
        if: ${{ github.event.action == 'labeled' && github.event.label.name == 'publish-required' }}
        template: ${{ github.workspace }}/.github/comments/publish_requested.md

      - uses: ./.github/actions/create-comment
        if: ${{ github.event.pull_request.user.login != 'CBenoit' }}
        if: ${{ github.event.action == 'labeled' && github.event.label.name == 'release-required' }}
        template: ${{ github.workspace }}/.github/comments/release_requested.md
