name: Release Assistant

on:
  pull_request:
    branches: [master]
    types: [opened, labeled]
  workflow_dispatch:
  schedule:
    - cron: '49 1 * * 1' # 1:49 AM UTC every Monday

jobs:
  create-comment:
    name: Create Comment
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login != 'CBenoit' && github.event.pull_request.user.login != 'dependabot' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - if: ${{ github.event.action == 'opened' }}
        uses: ./.github/actions/create-comment
        with:
          template: ${{ github.workspace }}/.github/comments/pr_greetings.md

      - if: ${{ github.event.action == 'labeled' && github.event.label.name == 'publish-required' }}
        uses: ./.github/actions/create-comment
        with:
          template: ${{ github.workspace }}/.github/comments/publish_requested.md

      - if: ${{ github.event.action == 'labeled' && github.event.label.name == 'release-required' }}
        uses: ./.github/actions/create-comment
        with:
          template: ${{ github.workspace }}/.github/comments/release_requested.md

  notify-slack:
    name: Notify Slack
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ARCHITECTURE }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    strategy:
      matrix:
        required-label: [release-required, publish-required]
        include:
          - required-label: release-required
            blocker-label: release-blocker
            message: Please cut a release
          - required-label: publish-required
            blocker-label: publish-blocker
            message: Please publish libraries

    steps:
      - uses: actions/checkout@v4

      - name: Verify labels
        id: verify-labels
        run: |
          Set-PSDebug -Trace 1

          $blockerCount = ./ci/pr-count-for-label.ps1 -Label '${{ matrix.blocker-label }}'

          if ($blockerCount -ne 0)
          {
            Write-Output "notify=no" >> $Env:GITHUB_OUTPUT
          }
          else
          {
            $requiredCount = ./ci/pr-count-for-label.ps1 -Label '${{ matrix.required-label }}'

            if ($requiredCount -ne 0)
            {
              Write-Output "notify=yes" >> $Env:GITHUB_OUTPUT
            }
            else
            {
              Write-Output "notify=no" >> $Env:GITHUB_OUTPUT
            }
          }
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Send slack notification
        id: slack
        if: ${{ steps.verify-labels.outputs.notify == 'yes' }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.repository }}* :recycle: \n ${{ matrix.message }} for *${{ github.repository }}*"
                  }
                }
              ]
            }
